@startuml

participant "Consumer" as consumer
participant "Association Register" as association
participant "Authorization Register (owner)" as ownerAr
participant "Resource (owner)" as ownerApi

consumer -> association : /token (get authentication token)
association -> association : check client assertion
association -> association : check consumer still compliant
association -> consumer  : OK: token
consumer -> association : /party (with token get owner party information)
association -> association : check token
association -> consumer  : OK: party info
consumer -> consumer : extract Authorization Register URL

consumer -> ownerAr : /token (get authentication token)
ownerAr -> ownerAr : check client assertion
ownerAr -> association : /token (get authentication token)
association -> association : check client assertion
association -> association : check AR still compliant
association -> ownerAr  : OK: token
ownerAr ->  association : /party (with token get consumer party information)
association -> association : check token
association -> ownerAr   : OK: party info
ownerAr -> ownerAr : check consumer party info for compliance
ownerAr -> consumer  : OK: token

consumer -> ownerAr : /delegation (with token and delegation mask)
ownerAr -> ownerAr : check token
ownerAr -> ownerAr : check delegation mask policies
ownerAr -> consumer  : OK: delegation evidence

consumer -> ownerApi : /token (get authentication token)
ownerApi -> ownerApi : check client assertion
ownerApi -> association : /token (get authentication token)
association -> association : check client assertion
association -> association : check owner still compliant
association -> ownerApi : OK: token
ownerApi -> association : /party (with token get consumer party information)
association -> association : check token
association -> ownerApi : OK: party info
ownerApi -> ownerApi : check consumer party info for compliance
ownerApi -> consumer : OK: token

consumer -> ownerApi : /some-resource (with token and delegation evidence)
ownerApi -> ownerApi : check token
ownerApi -> ownerApi : check delegation evidence
ownerApi -> consumer : OK: data

@enduml
